### ISSUE TITLE
SQLAlchemy 2.0 support

### ISSUE THREAD

**Issue by enginecan** [OleksandrZhydyk/FastAPI-SQLAlchemy-Filters#2]
Would be nice if you could add SQLAlchemy 2.0 support (including asyncio)

**Comment by enginecan** [comment]
from pydantic._internal._model_construction import ModelMetaclass in v2

**Comment by OleksandrZhydyk** [comment]
> Would be nice if you could add SQLAlchemy 2.0 support (including asyncio)

I'll do it soon, thanks

**Comment by OleksandrZhydyk** [comment]
the package upgraded to pydantic, sqlalchemy v2

**Comment by enginecan** [comment]
Would be nice to have an example of multi-table queries with bunch of joins
